name: ubuntu latest

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Await local workflow - qbt download and release reusable files for workflows
        if: env.trigger_files_workflow == 'yes'
        uses: codex-/await-local-workflow-run@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "test-run.yml"
          timeout_mins: 20
          poll_interval_ms: 10000
