name: ubuntu latest

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch latest GitHub tag
        id: fetch_latest_tag
        run: |
          latest_tag=$(gh release list --json tagName -L 1 -q '.[0].tagName')
          echo "LATEST_TAG=${latest_tag}" >> $GITHUB_ENV
          echo $latest_tag

      - name: test
        run: |
          echo "1: ${{ env.LATEST_TAG }}"
          echo "2: ${{ env.LATEST_TAG//+/ }}"
