name: test

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: trigger local workflow
        run: gh workflow run test-run.yml

      - name: Await local workflow
        uses: codex-/await-local-workflow-run@v1
        with:
          token: ${{ github.token }}
          workflow: "test-run.yml"
          timeout_mins: 20
          poll_interval_ms: 10000
