name: test iperf3 osx

on:
  workflow_dispatch:

jobs:
  test-amd64:
    runs-on: macos-13

    steps:
      - name: test iperf3
        run: |
          iperf3 --version

  test-arm64:
    runs-on: macos-latest

    steps:
      - name: test iperf3
        run: |
          iperf3 --version
