name: test

on:
  workflow_dispatch:
    inputs:
      fake_tag:
        description: "Set fake tag to force a build - 99.99.99"
        required: false
        default: ""

permissions:
  actions: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if fake_tag is provided
        if: ${{ github.event.inputs.fake_tag == '' }}
        run: |
          echo "no fakes here"

      - name: Check if fake_tag is provided
        if: ${{ github.event.inputs.fake_tag != '' }}
        run: |
          echo "fake_tag is provided: ${{ github.event.inputs.fake_tag }}"
