name: test iperf3 osx

on:
  workflow_dispatch:

jobs:
  test-amd64:
    runs-on: macos-13

    steps:
      - name: test iperf3 version
        run: |
          wget -O ~/iperf3 "https://github.com/userdocs/iperf3-static/releases/latest/download/iperf3-amd64-osx-13"
          chmod +x ~/iperf3

          printf '\n%b\n\n' "🟦"
          file ~/iperf3

          printf '\n%b\n\n' "🟦"
          otool -L ~/iperf3

          printf '\n%b\n\n' "🟦"
          ~/iperf3 --version

      - name: test iperf3 servers
        run: |
          ~/$(wget -qO- https://db.iperf3serverlist.net/api/v1/db/public/shared-view/b111407c-43c4-48af-a828-301b698064a3/rows/export/csv | awk -F, 'NR>1 { print $1 }' | shuf -n1)

  test-arm64:
    runs-on: macos-latest

    steps:
      - name: test iperf3 version
        run: |
          wget -O ~/iperf3 "https://github.com/userdocs/iperf3-static/releases/latest/download/iperf3-arm64-osx-14"
          chmod +x ~/iperf3

          printf '\n%b\n\n' "🟦"
          file ~/iperf3

          printf '\n%b\n\n' "🟦"
          otool -L ~/iperf3

          printf '\n%b\n\n' "🟦"
          ~/iperf3 --version

      - name: test iperf3 servers
        run: |
          ~/$(wget -qO- https://db.iperf3serverlist.net/api/v1/db/public/shared-view/b111407c-43c4-48af-a828-301b698064a3/rows/export/csv | awk -F, 'NR>1 { print $1 }' | shuf -n1)
