name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            target: x86_64-apple-darwin
          - arch: arm64
            target: arm64-apple-darwin

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          brew update || brew update-reset
          brew install autoconf automake libtool

      - name: Clone iperf3 repository
        run: git clone https://github.com/esnet/iperf.git iperf3

      - name: Set CC
        run: echo "CC=clang -target ${{ matrix.target }}$(uname -r)" >> "$GITHUB_ENV"

      - name: Build
        working-directory: iperf3
        run: ./bootstrap.sh

      - name: configure
        working-directory: iperf3
        run: ./configure --host="${{ matrix.target }}$(uname -r)" --disable-silent-rules --disable-profiling --prefix=${{ github.workspace }}/build

      - name: make
        working-directory: iperf3
        run: make -j"$(sysctl -n hw.logicalcpu)"

      - name: make install
        working-directory: iperf3
        run: make install

      - name: test
        run: |
          file ./build/bin/iperf3
          ldd ./build/bin/iperf3

      - name: copy
        working-directory: iperf3
        run: |
          cp ./src/iperf3 ${{ github.workspace }}/iperf3-macos-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iperf3-macos-${{ matrix.arch }}
          path: ${{ github.workspace }}/build

      - name: Upload artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: config.log
          path: ${{ github.workspace }}/iperf3/config.log
