# .github/workflows/docker-multiarch.yml
name: Build and Push Docker Multiarch Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          ["amd64", "arm64", "arm/v6", "arm/v7", "s390x", " ppc64le", "386"]
        include:
          - platform: "amd64"
            URL: "iperf3-amd64"
          - platform: "arm/v6"
            URL: "iperf3-arm32v6"
          - platform: "arm/v7"
            URL: "iperf3-arm32v7"
          - platform: "arm64"
            URL: "iperf3-arm64v8"
          - platform: "s390x"
            URL: "iperf3-s390x"
          - platform: "ppc64le"
            URL: "iperf3-ppc64le"
          - platform: "386"
            URL: "iperf3-i386"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          platforms: linux/${{ matrix.platform }}
          build-args: |
            PLATFORM=linux/${{ matrix.platform }}
            URL=${{ matrix.URL }}
